apiVersion: argroj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-test
  namespace: argocd
spec:
  project: default
  source:
    # --- Dati del Chart Helm ---
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 4.6.10 # Versione stabile del chart

    # --- NO HELM VALUES (usiamo i default del chart) ---
    helm: {} # Blocco helm vuoto

  # --- Destinazione (Namespace dove installare Nextcloud) ---
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud-test # Usiamo un namespace diverso per non creare conflitti

  # --- Sync Policy ---
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Chiediamo ad Argo di creare il namespace