# File: k3s-quiris-01/argocd/applications/seafile.yaml
apiVersion: argroj.io/v1alpha1
kind: Application
metadata:
  name: seafile
  namespace: argocd
spec:
  project: default
  source:
    # --- Repository Helm (Usiamo un chart comune, verifica se ne esistono di ufficiali migliori) ---
    repoURL: https://charts.helm.sh/stable 
    # NOTA: Il repo 'stable' è deprecato, ma potrebbe contenere ancora vecchi chart.
    # CERCA UN CHART SEAFILE PIÙ AGGIORNATO su Artifact Hub se questo non funziona.
    # Per esempio, potresti trovare alternative qui: https://artifacthub.io/packages/search?ts_query_web=seafile&sort=relevance&page=1
    chart: seafile-server 
    targetRevision: 0.1.0 # Versione specifica del chart (potrebbe essere obsoleta)

    helm:
      values: |
        image:
          # Verifica l'ultima versione stabile di Seafile Community Edition
          tag: "9.0.9" 

        # L'admin user si crea al primo accesso

        ingress:
          enabled: true
          ingressClassName: "nginx" # Il nostro ingress-nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy_body_size: "0" # Per upload grandi
          hosts:
            - host: "seafile.agnenergia.com" # ❗️ USA IL TUO VERO HOSTNAME DNS
              paths:
                - path: /
                  pathType: Prefix
          # tls: # Aggiungi se userai cert-manager
          #   - secretName: seafile-tls-secret
          #     hosts:
          #       - seafile.agnenergia.com

        # Disabilita DB Interno
        mariadb:
          enabled: false

        # Configura DB Esterno PostgreSQL
        externalDatabase:
          enabled: true
          type: postgresql
          host: "k3s-db.default.svc.cluster.local" # Nome DNS completo interno a K8s
          port: 5432
          username: "seafileuser"
          existingSecret: "seafile-db-secret" # Nome del secret creato
          secretPasswordKey: "password"      # Chiave nel secret
          databaseNames:
            ccnet: "ccnetdb"
            seafile: "seafiledb"
            seahub: "seahubdb"

        # Configura Storage NFS
        persistence:
          enabled: true
          storageClassName: "nfs-client" # La nostra StorageClass NFS
          accessMode: ReadWriteOnce      # Seafile richiede RWO
          size: 100Gi                  # Spazio dati iniziale

        # Disabilita Elasticsearch e Memcached interni (se presenti nel chart)
        elasticsearch:
          enabled: false
        memcached:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: seafile # Namespace di destinazione

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true