# app-manifest.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  
  source:
    # Puntiamo all'Helm Chart ufficiale di Nextcloud
    repoURL: 'https://nextcloud.github.io/helm/'
    chart: 'nextcloud'
    targetRevision: '3.5.5' # Specifica una versione del chart per stabilità
    
    helm:
      # Argo CD prenderà i values dal *nostro* repo Git
      valueFiles:
        - 'https://raw.githubusercontent.com/quirishld/k3s-quiris-01/main/apps/nextcloud/helm-values.yaml'
        # ^-- ATTENZIONE: Usa l'URL "raw" del tuo file helm-values.yaml su GitHub
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextcloud # L'app sarà deployata in un suo namespace
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Argo CD creerà il namespace 'nextcloud'
