apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.186
    path: /srv/nfs/nextcloud-fresh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-pv
  storageClassName: ""  # <-- AGGIUNGI QUESTA RIGA
---


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Il nome della tua applicazione in Argo CD
  name: nextcloud
  # Il namespace in cui risiede Argo CD stesso
  namespace: argocd
spec:
  # Il progetto Argo CD a cui questa app apparterrà (spesso 'default')
  project: default

  # Configurazione della sorgente (il chart Helm)
  source:
    # L'URL del repository Helm di Nextcloud
    repoURL: https://nextcloud.github.io/helm/
    # Il nome del chart nel repository
    chart: nextcloud
    # Specifica la versione del chart che vuoi deployare
    # Si consiglia di bloccare una versione specifica per la stabilità
    targetRevision: '8.5.1' # Sostituisci con la versione desiderata

    # Qui puoi sovrascrivere i valori di default del chart (values.yaml)
    helm:
      values: |
        # Esempio: Configurazione dell'Ingress
        ingress:
          enabled: true
          className: "nginx" # Sostituisci con la tua classe Ingress (es. traefik, nginx)
          annotations:
            # Esempio: annotazioni per cert-manager (opzionale)
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: nextcloud.agnenergia.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
           - secretName: nextcloud-tls
             hosts:
               - nextcloud.agnenergia.com

        # Configurazione della persistenza (MOLTO IMPORTANTE)
        # Assicurati di avere un provisioner di StorageClass nel tuo cluster
        persistence:
          enabled: true
          
          # 1. NON usiamo più 'existingClaim'
          # existingClaim: nextcloud-pvc
          
          # 2. CHIEDIAMO al provisioner di crearci un volume
          storageClass: "nfs-client" # <-- Il nome che abbiamo definito sopra
          
          # 3. L'NFS è ReadWriteMany (RWX)
          accessModes:
            - ReadWriteMany
          size: 10Gi

        # Configurazione del database interno (per test/demo)
        # Per produzione, si consiglia vivamente un database ESTERNO (es. PostgreSQL o MariaDB)
        mariadb:
          enabled: false # Imposta a 'false' se usi un database esterno
          db:
            user: nextcloud
            database: nextcloud
          # È FONDAMENTALE impostare una password sicura
          # Si consiglia di gestirla tramite un Secret esterno o SealedSecret
          auth:
            rootPassword: "cambiami-password-root-sicura"
            password: "cambiami-password-utente-sicura"

        externalDatabase:
          enabled: true
          type: postgresql
          host: 10.10.10.190
          database: nextcloud
          user: nextcloud_user
          password: "Cerauncagnonenelbosco2025"


        # Impostazioni di Nextcloud
        nextcloud:
          host: nextcloud.agnenergia.com
          # Imposta le credenziali dell'amministratore di Nextcloud
          # Anche queste dovrebbero essere gestite tramite Secret
          existingSecret:
            enabled: false # Imposta a 'true' e specifica 'secretName' se usi un Secret
          username: admin
          password: "cambiami-password-admin-sicura"

        # -----------------------------------------------------------------
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1000m       # 1 CPU
            memory: 6Gi        # 2 Gigabyte di RAM



  # Configurazione della destinazione (il tuo cluster Kubernetes)
  destination:
    # L'URL del server Kubernetes (lascia 'https://kubernetes.default.svc' per il cluster locale)
    server: https://kubernetes.default.svc
    # Il namespace in cui vuoi installare Nextcloud
    namespace: nextcloud

  # Policy di sincronizzazione
  syncPolicy:
    automated:
      # Argo CD creerà automaticamente le risorse che non esistono
      prune: true
      # Argo CD sincronizzerà automaticamente quando rileva modifiche nel Git/Helm repo
      selfHeal: true
    syncOptions:
      # Crea il namespace 'nextcloud' se non esiste
      - CreateNamespace=true