apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  
  # --- Sorgente: Helm Chart Ufficiale ---
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    # Usiamo una versione recente del chart
    targetRevision: '8.5.1' 
    
    helm:
      values: |
        # --- Configurazione Generale di Nextcloud ---
        nextcloud:
          host: "nextcloud.agnenergia.com" # Il tuo dominio
          username: "nc-admin"              # Il tuo utente admin
          password: "Cerauncagnonenelbosco2025!" # La tua password admin

        # --- Configurazione Ingress (per k3s/Traefik) ---
        ingress:
          enabled: true
          className: "traefik" # Default per k3s
          annotations:
            # Abilita cert-manager per SSL automatico
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls:
            - secretName: nextcloud-tls
              hosts:
                - "nextcloud.agnenergia.com" 

        # --- Abilita il Database interno (MariaDB) ---
        # Questo crea un database per te
        mariadb:
          enabled: true
          auth:
            rootPassword: "CAMBIAMI_PASSWORD_DB_ROOT_SECRETA"
            password: "CAMBIAMI_PASSWORD_DB_NEXTCLOUD_SECRETA"

        # --- Abilita Redis interno (per caching e file locking) ---
        redis:
          enabled: true
          
        # --- Configurazione della Persistenza (Storage) ---
        # Usa il 'local-path' provisioner predefinito di k3s
        persistence:
          enabled: true
          storageClass: "local-path"
          size: 10Gi # Puoi aumentare questo valore

        # Consigliato per migliorare le prestazioni
        cronjob:
          enabled: true

        # Disabilita il LoadBalancer, useremo Ingress
        service:
          type: ClusterIP

  # --- Destinazione: Dove installare ---
  destination:
    server: https://kubernetes.default.svc
    # Installiamo nel namespace 'nextcloud' (come nel tuo file)
    namespace: nextcloud 

  # --- Sync Policy ---
  syncPolicy:
    automated:
      prune: true    
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true # Argo CD creerà il namespace 'nextcloud'