apiVersion: argroj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argócé
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  project: default
  
  # --- Sorgente: Helm Chart Ufficiale ---
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: '8.5.1' # <-- NOTA: Questa è una versione vecchia del chart, considera l'ultima (es. 4.6.10)
    
    helm:
      values: |
        # --- Configurazione Generale di Nextcloud ---
        nextcloud:
          host: "nextcloud.agnenergia.com" 
          username: "nc-admin"              
          password: "Cerauncagnonenelbosco2025!" # Password Admin di Nextcloud

          # --- Storage per la Configurazione ---
          persistence:
            enabled: true
            storageClass: "nfs-client" # <-- Ripristinato per la config
            accessMode: ReadWriteOnce 
            size: 1Gi               

        # --- Configurazione Ingress ---
        ingress:
          enabled: true
          className: "nginx" 
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "1024m" 
          hosts:
            - host: "nextcloud.agnenergia.com" 
              paths:
                - path: /
                  pathType: Prefix

        # --- Database Interno Disabilitato ---
        mariadb:
          enabled: false
        postgresql: # Assicurati sia disabilitato anche questo se presente nel chart
          enabled: false 

        # --- MANTENUTO: Redis interno ---
        redis:
          enabled: true
          
        # =========================================================
        # --- CORRETTO: Configurazione Database Esterno ---
        # =========================================================
        externalDatabase:
          enabled: true
          type: "postgresql"
          host: "k3s-db"             # Nome DNS server DB
          database: "nextclouddb"     # Nome DB creato
          user: "nextclouduser"     # Utente DB creato
          # Prende la password dal secret 'nextcloud-db-secret'
          password: "Cerauncagnonenelbosco2025!" # Password Admin di Nextcloud
            
        # --- Configurazione della Persistenza (Storage DATI) ---
        persistence:
          enabled: true
          storageClass: "nfs-client"
          accessMode: ReadWriteMany # <-- Importante per i dati con NFS
          size: 50Gi # O quanto spazio vuoi dare ai dati

        cronjob:
          enabled: true
        service:
          type: ClusterIP

  # --- Destinazione: Dove installare ---
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud 

  # --- Sync Policy ---
  syncPolicy:
    automated:
      prune: true    
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true