apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Aggiunto per pulizia
spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 4.6.10

    helm:
      values: |
        # ================================================================
        # --- 1. Blocco 'nextcloud:' UNITO E CORRETTO ---
        # ================================================================
        nextcloud:
          # --- Configurazione Admin e Dominio (dal tuo file) ---
          username: "nc-admin"
          password: "Cerauncagnonenelbosco2025!" 
          host: "nextcloud.agnenergia.com"

          # --- Configurazione Storage per /var/www/html/config (dal tuo file) ---
          # È corretto tenerlo separato dai dati principali
          persistence:
            enabled: true
            storageClass: "nfs-client"
            accessMode: ReadWriteOnce 
            size: 1Gi
        
          # ================================================================
          # --- 2. Configurazione Database CORRETTA ---
          # ================================================================
          # Il chart 4.6.10 usa 'nextcloud.database', non 'externalDatabase'
          database:
            type: "postgresql"
            # NOTA: 'k3s-db' funziona solo se il DB è nello stesso namespace ('nextcloud')
            # Altrimenti usa 'k3s-db.<namespace-del-db>.svc.cluster.local'
            host: "k3s-db"
            user: "nextclouduser"
            database: "nextclouddb"
            
            # --- Gestione Password DB ---
            # Stai usando un secret, che è un'ottima pratica.
            # Assicurati che questo segreto esista nel namespace 'nextcloud'
            # (Lo creo con: kubectl create secret generic nextcloud-db-secret -n nextcloud --from-literal=password=LA_TUA_PASSWORD_DB)
            passwordSecret:
              name: "nextcloud-db-secret"
              key: "password"

        # ================================================================
        # --- 3. Configurazione Ingress (Accesso Esterno) ---
        # ================================================================
        ingress:
          enabled: true
          # NOTA: Ho cambiato 'nginx' in 'traefik', che è il default di k3s.
          # Se usi N