apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Il nome della tua applicazione in Argo CD
  name: nextcloud
  # Il namespace in cui risiede Argo CD stesso
  namespace: argocd
spec:
  # Il progetto Argo CD a cui questa app apparterrà (spesso 'default')
  project: default

  # Configurazione della sorgente (il chart Helm)
  source:
    # L'URL del repository Helm di Nextcloud
    repoURL: https://nextcloud.github.io/helm/
    # Il nome del chart nel repository
    chart: nextcloud
    # Specifica la versione del chart che vuoi deployare
    # Si consiglia di bloccare una versione specifica per la stabilità
    targetRevision: '8.5.1' # Sostituisci con la versione desiderata

    # Qui puoi sovrascrivere i valori di default del chart (values.yaml)
    helm:
      values: |
        # Esempio: Configurazione dell'Ingress

        ingress:
          enabled: true
          className: "nginx" # Sostituisci con la tua classe Ingress (es. traefik, nginx)
          annotations:
            # Esempio: annotazioni per cert-manager (opzionale)
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: nextcloud.agnenergia.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
           - secretName: nextcloud-tls
             hosts:
               - nextcloud.agnenergia.com

        # Configurazione della persistenza (MOLTO IMPORTANTE)
        # Assicurati di avere un provisioner di StorageClass nel tuo cluster
        persistence:
          enabled: true
          storageClass: "local-path"  #"nfs-clientlocal-path" # Sostituisci con la tua StorageClass (es. ceph-rbd, longhorn)
          accessMode: ReadWriteOnce
          size: 10Gi # Aumenta la dimensione in base alle tue necessità

        # Configurazione del database interno (per test/demo)
        # Per produzione, si consiglia vivamente un database ESTERNO (es. PostgreSQL o MariaDB)
        mariadb:
          enabled: false # Imposta a 'false' se usi un database esterno
          db:
            user: nextcloud
            database: nextcloud
          # È FONDAMENTALE impostare una password sicura
          # Si consiglia di gestirla tramite un Secret esterno o SealedSecret
          auth:
            rootPassword: "cambiami-password-root-sicura"
            password: "cambiami-password-utente-sicura"

        internalDatabase:
          enabled: false # Disabilitiamo il MariaDB interno

        externalDatabase:
          enabled: true
          type: "postgresql"
          host: "10.10.10.190"
          database: "nextcloud"
          user: "nextcloud_user"
          passwordSecret:
            name: "nextcloud-db-secret" # Creeremo questo segreto manualmente
            key: "password"


        # Impostazioni di Nextcloud
        nextcloud:
          host: nextcloud.agnenergia.com
          # Imposta le credenziali dell'amministratore di Nextcloud
          # Anche queste dovrebbero essere gestite tramite Secret
          existingSecret:
            enabled: false # Imposta a 'true' e specifica 'secretName' se usi un Secret
          username: admin
          password: "cambiami-password-admin-sicura"

  # Configurazione della destinazione (il tuo cluster Kubernetes)
  destination:
    # L'URL del server Kubernetes (lascia 'https://kubernetes.default.svc' per il cluster locale)
    server: https://kubernetes.default.svc
    # Il namespace in cui vuoi installare Nextcloud
    namespace: nextcloud

  # Policy di sincronizzazione
  syncPolicy:
    automated:
      # Argo CD creerà automaticamente le risorse che non esistono
      prune: true
      # Argo CD sincronizzerà automaticamente quando rileva modifiche nel Git/Helm repo
      selfHeal: true
    syncOptions:
      # Crea il namespace 'nextcloud' se non esiste
      - CreateNamespace=true