apiVersion: argroj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 4.6.10 # Versione stabile del chart

    # --- Configurazione specifica per questo chart ---
    helm:
      values: |
        # 1. Configurazione Admin
        nextcloud:
          username: "nc-admin"
          password: "Cerauncagnonenelbosco2025!" # ❗️ Scegli una password robusta
          host: "nextcloud.agnenergia.com"     # ❗️ Usa il tuo vero dominio/hostname

        # 2. Configurazione Ingress (Accesso Esterno)
        ingress:
          enabled: true
          className: "nginx" # Specifica che useremo ingress-nginx
          annotations:
            # Opzionale: Se vuoi forzare HTTPS (richiede Cert-Manager o config manuale SSL)
            # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            # Opzionale: Per file grandi (aumenta il limite di upload)
            nginx.ingress.kubernetes.io/proxy-body-size: "1024m" 
          hosts:
            - host: "nextcloud.agnenergia.com" # ❗️ Usa il tuo vero dominio/hostname
              paths:
                - path: /
                  pathType: Prefix
          # Opzionale: Se gestirai SSL con Cert-Manager
          # tls:
          #   - secretName: nextcloud-tls-secret # Nome del secret con il certificato
          #     hosts:
          #       - nextcloud.agnenergia.com

        # 3. Disabilita DB/Redis interni del chart
        postgresql:
          enabled: false
        mariadb:
          enabled: false
        redis:
          enabled: false # Usiamo quello esterno se lo abbiamo, altrimenti ne crea uno semplice

        # 4. Collega il nostro DB esterno PostgreSQL
        externalDatabase:
          type: "postgresql"
          host: "k3s-db"             # Nome DNS del server DB
          database: "nextclouddb"     # Nome DB creato
          user: "nextclouduser"     # Utente DB creato
          # Prende la password dal secret che creeremo tra poco
          passwordSecret:
            name: "nextcloud-db-secret"
            key: "password"

        # 5. Configura lo Storage NFS
        persistence:
          enabled: true
          storageClass: "nfs-client" # Usa la nostra StorageClass NFS!
          accessMode: ReadWriteMany  # NFS supporta RWX, utile per Nextcloud
          size: 100Gi              # Quantità di spazio iniziale per i file
          # Nota: Questa è la cartella dei DATI (/var/www/html/data)

        # 6. Configura lo storage per la config di Nextcloud (/var/www/html/config etc.)
        #    Usiamo anche NFS per questo, ma con un volume separato.
        nextcloud:
          persistence:
            enabled: true
            storageClass: "nfs-client"
            accessMode: ReadWriteOnce # RWO è sufficiente per la config
            size: 1Gi               # 1GB basta per la config
  
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true