apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18

    # --- THIS IS THE KEY CHANGE ---
    # The 'values' block must be under 'helm'
    helm:
      values: |
        # Tell the provisioner where your NFS server is
        nfs:
          # --- ❗️ REPLACE THESE VALUES ---
          server: 10.10.10.186             # IP address of your k3s-nfs-server VM
          path: /srv/nfs/kubedata          # The exact export path you configured
          # ------------------------------
          mountOptions:
            - nfsvers=4.1 # Use a modern NFS version

        # Define the StorageClass that applications will use
        storageClass:
          create: true
          defaultClass: true         # Make this the new default storage
          name: nfs-client         # Name of the StorageClass
          allowVolumeExpansion: true
          reclaimPolicy: Retain      # Keep data even if PVC is deleted (safer)
          archiveOnDelete: false
    # --- END OF HELM VALUES ---

  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
