apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Repository ufficiale dei chart Seafile
    repoURL: https://seafile.github.io/seafile-helm
    chart: seafile
    targetRevision: 2.7.2 # Una versione stabile recente

    helm:
      values: |
        # --- Configurazione Ingress (per NGINX) ---
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            # Sostituisco il dominio, usa quello che preferisci
            - host: "seafile.agnenergia.com" # <-- MODIFICA SE NECESSARIO
          annotations:
            # Fondamentale per l'upload di file grandi!
            nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
        
        # --- Disabilita i componenti interni ---
        mariadb:
          enabled: false
        elasticsearch:
          enabled: false # Funzione di ricerca (non necessaria per iniziare)
        redis:
          enabled: false # Seafile abilita memcached di default, che è sufficiente

        # --- Configurazione Database Esterno (PostgreSQL) ---
        externalDatabase:
          enabled: true
          type: postgresql
          host: "k3s-db" # Il tuo host (via /etc/hosts)
          
          # I nomi dei 3 DB che hai creato al Passo 1
          ccnetDbName: "seafile_ccnet_db"
          seafileDbName: "seafile_db"
          seahubDbName: "seafile_seahub_db"
          
          user: "seafileuser" # L'utente creato
          password: "Cerauncagnonenelbosco2025!" # <-- Inserisci la password

        # --- Configurazione Storage (NFS) ---
        persistence:
          storageClass: "nfs-client" # La tua StorageClass
          size: 50Gi 

        # --- Configurazione Amministratore Seafile ---
        # All'avvio, Seafile creerà questo utente
        seafile:
          adminUser: "admin@seafile.local" # <-- Puoi cambiarlo
          adminPassword: "PasswordAdminSeafile!" # <-- CAMBIA QUESTO

        # --- Importante per i permessi NFS ---
        # Molti chart usano UID/GID 1000 di default.
        securityContext:
          runAsUser: 1000
          fsGroup: 1000

  destination:
    server: https://kubernetes.default.svc
    namespace: seafile # Installiamo in un nuovo namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true