apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Il nome della tua applicazione in Argo CD
  name: seafile
  # Indica ad Argo CD di gestire le risorse in questo namespace
  namespace: argocd
spec:
  project: default

  # Configurazione di Sincronizzazione (Opzionale ma utile)
  syncPolicy:
    automated:
      prune: true    # Rimuove le vecchie risorse
      selfHeal: true # Si assicura che lo stato desiderato sia mantenuto
    syncOptions:
      - CreateNamespace=true # Argo CD creerà il namespace 'seafile' se non esiste

  # DESTINAZIONE: Dove installare
  destination:
    server: https://kubernetes.default.svc
    # Il namespace dove Seafile verrà installato (lo stesso del secret)
    namespace: seafile

  # SORGENTE: Cosa installare (il chart Helm)
  source:
    # L'URL del repository Helm di Seafile
    repoURL: https://haiwen.github.io/seafile-helm-chart/repo
    # Il nome del chart
    chart: seafile
    # Specifica una versione per installazioni stabili
    targetRevision: 2.5.4 # Puoi cambiare alla versione più recente

    # Qui inseriamo l'equivalente del nostro 'values.yaml'
    helm:
      values: |
        # Configura l'URL con cui accederai a Seafile.
        # Sostituisci 'seafile.tuodominio.com' con il tuo vero dominio.
        seafile:
          server:
            hostname: "seafile.tuodominio.com"

        # Abilita l'Ingress (per Traefik su k3s)
        ingress:
          enabled: true
          hosts:
            - seafile.tuodominio.com
          # Se usi Let's Encrypt (richiede setup di cert-manager o Traefik):
          # tls:
          #   - secretName: seafile-tls-secret
          #     hosts:
          #       - seafile.tuodominio.com

        # Abilita la persistenza
        persistence:
          enabled: true
          storageClassName: "local-path" # 'local-path' è default su k3s
          size: 50Gi

        # Abilita le dipendenze
        mariadb:
          enabled: true
          persistence:
            enabled: true
            storageClassName: "local-path"
            size: 10Gi

        memcached:
          enabled: true

        # Collega il secret creato manualmente.
        # Il chart prenderà le password da 'seafile-secret'
        secrets:
          dbRootPasswordKey: DB_ROOT_PASSWD
          dbPasswordKey: DB_PASSWORD
          adminPasswordKey: INIT_SEAFILE_ADMIN_PASSWORD
          jwtPrivateKey: JWT_PRIVATE_KEY