apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile
  namespace: argcd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # ================================================================
    # --- ECCO LA CORREZIONE ---
    repoURL: https://seafile.github.io/seafile-helm
    # ================================================================
    chart: seafile
    targetRevision: 2.7.2 # Questa versione è valida

    helm:
      values: |
        # --- Configurazione Ingress (per NGINX) ---
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: "seafile.agnenergia.com" 
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
        
        # --- Disabilita i componenti interni ---
        mariadb:
          enabled: false
        elasticsearch:
          enabled: false 
        redis:
          enabled: false 

        # --- Configurazione Database Esterno (PostgreSQL) ---
        externalDatabase:
          enabled: true
          type: postgresql
          host: "k3s-db" 
          
          ccnetDbName: "seafile_ccnet_db"
          seafileDbName: "seafile_db"
          seahubDbName: "seafile_seahub_db"
          
          user: "seafileuser" 
          password: "Cerauncagnonenelbosco2025!" # <-- Inserisci la password

        # --- Configurazione Storage (NFS) ---
        persistence:
          storageClass: "nfs-client" 
          size: 50Gi 

        # --- Configurazione Amministratore Seafile ---
        seafile:
          adminUser: "admin@seafile.local" 
          adminPassword: "PasswordAdminSeafile!" # <-- CAMBIA QUESTO

        # --- Importante per i permessi NFS ---
        securityContext:
          runAsUser: 1000
          fsGroup: 1000

  destination:
    server: https://kubernetes.default.svc
    namespace: seafile 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true