apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # ================================================================
    # --- NUOVO REPO (grom/seafile) ---
    repoURL: https://grom.github.io/charts
    chart: seafile
    # Usiamo una versione recente di questo chart
    targetRevision: 3.0.0 
    # ================================================================

    helm:
      values: |
        # --- Configurazione Ingress (per NGINX) ---
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: "seafile.agnenergia.com" 
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
            # Questo chart richiede un'annotazione per il backend
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        
        # --- Disabilita i componenti interni ---
        mariadb:
          enabled: false
        memcached:
          enabled: false # Disabilitiamo tutto, useremo Redis
        
        # --- Usiamo Redis (raccomandato da questo chart) ---
        redis:
          enabled: true

        # --- Configurazione Database Esterno (PostgreSQL) ---
        # La struttura è leggermente diversa
        externalDatabase:
          type: "postgresql"
          host: "k3s-db" 
          user: "seafileuser" 
          password: "Cerauncagnonenelbosco2025!" # La tua password del DB
          
          # I nomi dei 3 DB
          db_name_ccnet: "seafile_ccnet_db"
          db_name_seafile: "seafile_db"
          db_name_seahub: "seafile_seahub_db"

        # --- Configurazione Storage (NFS) ---
        persistence:
          storageClass: "nfs-client" 
          size: 50Gi 

        # --- Configurazione Amministratore Seafile ---
        seafile:
          adminEmail: "admin@seafile.local" # <-- Puoi cambiarlo
          adminPassword: "PasswordAdminSeafile!" # <-- CAMBIA QUESTO

  destination:
    server: https://kubernetes.default.svc
    namespace: seafile 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true